services:
  app:
    build: .
    container_name: news-agent
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "run", "dev"]

volumes:
  singlestore_data:
